# This is a basic workflow to help you get started with Actions

name: pickup-scheduler

# Controls when the action will run. 
on:
  schedule:
    - cron:  '4 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-scheduler:
    name: Run Pickup Scheduler
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # this Action should follow steps to set up Python build environment https://github.com/marketplace/actions/python-dependency-installation
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: Run python scheduler script
        run:
            python pickup-automation.py
        env:
          USER_ID: ${{ secrets.USPS_USER_ID }}
          ADDRESS: ${{ secrets.ADDRESS }}
          PHONE: ${{ secrets.PHONE }}
